version: "3.8"

services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
      context: .
      args:
        USERID: 1000
    command: php -S 0.0.0.0:8000 -t public
    volumes:
      - .:/srv
    tmpfs:
      - /srv/var:uid=1000,gid=1000
    ports:
      - 8000:8000