<?php

namespace Infrastructure\Persistence\Mysql;

use Domain\Models\Entity\CookingStepRepository;
use Domain\Models\Entity\CookingStep;

class CookingStepMysqlRepository extends AbstractMysqlRepository implements CookingStepRepository
{
    protected string $entityClassname = CookingStep::class;

    public function save(object $entity): void
    {
//        if ($)
        parent::save($entity); // TODO: Change the autogenerated stub
    }
}
